<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrePurchaseOrdersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $prePurchaseOrders = [
            [
                'po_number' => 'PPO-2025-001',
                'issue_date' => '2025-08-20',
                'supplier_id' => 1,
                'notes' => 'Planned purchase for September',
                'total_amount' => 2250000.00,
                'tax' => 225000.00,
                'due_date' => '2025-09-05',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'converted',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-002',
                'issue_date' => '2025-08-22',
                'supplier_id' => 2,
                'notes' => 'Coffee supply planning',
                'total_amount' => 1800000.00,
                'tax' => 180000.00,
                'due_date' => '2025-09-07',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'approved',
                'payment_method' => 'credit',
            ],
            [
                'po_number' => 'PPO-2025-003',
                'issue_date' => '2025-08-25',
                'supplier_id' => 3,
                'notes' => 'Cigarette bulk purchase proposal',
                'total_amount' => 3150000.00,
                'tax' => 315000.00,
                'due_date' => '2025-09-10',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'converted',
                'payment_method' => 'cash',
            ],
            [
                'po_number' => 'PPO-2025-004',
                'issue_date' => '2025-08-28',
                'supplier_id' => 4,
                'notes' => 'Tea products procurement',
                'total_amount' => 920000.00,
                'tax' => 92000.00,
                'due_date' => '2025-09-12',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'status' => 'pending',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-005',
                'issue_date' => '2025-09-01',
                'supplier_id' => 5,
                'notes' => 'Premium coffee selection proposal',
                'total_amount' => 1700000.00,
                'tax' => 170000.00,
                'due_date' => '2025-09-15',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'approved',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-006',
                'issue_date' => '2025-09-03',
                'supplier_id' => 6,
                'notes' => 'Monthly cigarette restock plan',
                'total_amount' => 2750000.00,
                'tax' => 275000.00,
                'due_date' => '2025-09-18',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'draft',
                'payment_method' => 'cash',
            ],
            [
                'po_number' => 'PPO-2025-007',
                'issue_date' => '2025-09-05',
                'supplier_id' => 7,
                'notes' => 'Snack and beverages procurement',
                'total_amount' => 1200000.00,
                'tax' => 120000.00,
                'due_date' => '2025-09-20',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'status' => 'approved',
                'payment_method' => 'debit',
            ],
            [
                'po_number' => 'PPO-2025-008',
                'issue_date' => '2025-09-07',
                'supplier_id' => 8,
                'notes' => 'Emergency stock planning',
                'total_amount' => 1620000.00,
                'tax' => 162000.00,
                'due_date' => '2025-09-22',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'pending',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-009',
                'issue_date' => '2025-09-10',
                'supplier_id' => 9,
                'notes' => 'Q4 coffee bulk purchase proposal',
                'total_amount' => 2150000.00,
                'tax' => 215000.00,
                'due_date' => '2025-09-25',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'converted',
                'payment_method' => 'credit',
            ],
            [
                'po_number' => 'PPO-2025-010',
                'issue_date' => '2025-09-12',
                'supplier_id' => 10,
                'notes' => 'Mixed products procurement plan',
                'total_amount' => 1380000.00,
                'tax' => 138000.00,
                'due_date' => '2025-09-27',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'status' => 'draft',
                'payment_method' => 'cash',
            ],
            [
                'po_number' => 'PPO-2025-011',
                'issue_date' => '2025-09-14',
                'supplier_id' => 11,
                'notes' => 'Year-end stock preparation proposal',
                'total_amount' => 3050000.00,
                'tax' => 305000.00,
                'due_date' => '2025-09-30',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'approved',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-012',
                'issue_date' => '2025-09-16',
                'supplier_id' => 12,
                'notes' => 'Tea variety expansion plan',
                'total_amount' => 850000.00,
                'tax' => 85000.00,
                'due_date' => '2025-10-02',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'pending',
                'payment_method' => 'debit',
            ],
            [
                'po_number' => 'PPO-2025-013',
                'issue_date' => '2025-09-18',
                'supplier_id' => 13,
                'notes' => 'Premium cigarette brands proposal',
                'total_amount' => 4100000.00,
                'tax' => 410000.00,
                'due_date' => '2025-10-05',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'status' => 'approved',
                'payment_method' => 'cash',
            ],
            [
                'po_number' => 'PPO-2025-014',
                'issue_date' => '2025-09-20',
                'supplier_id' => 14,
                'notes' => 'New supplier trial proposal',
                'total_amount' => 720000.00,
                'tax' => 72000.00,
                'due_date' => '2025-10-07',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'draft',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-015',
                'issue_date' => '2025-09-22',
                'supplier_id' => 15,
                'notes' => 'October stock preparation',
                'total_amount' => 2600000.00,
                'tax' => 260000.00,
                'due_date' => '2025-10-10',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'converted',
                'payment_method' => 'credit',
            ],
            [
                'po_number' => 'PPO-2025-016',
                'issue_date' => '2025-09-24',
                'supplier_id' => 1,
                'notes' => 'November planning preparation',
                'total_amount' => 1950000.00,
                'tax' => 195000.00,
                'due_date' => '2025-10-12',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'status' => 'pending',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-017',
                'issue_date' => '2025-09-25',
                'supplier_id' => 2,
                'notes' => 'Holiday season stock proposal',
                'total_amount' => 2800000.00,
                'tax' => 280000.00,
                'due_date' => '2025-10-15',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'approved',
                'payment_method' => 'cash',
            ],
            [
                'po_number' => 'PPO-2025-018',
                'issue_date' => '2025-09-26',
                'supplier_id' => 3,
                'notes' => 'Special promotion items',
                'total_amount' => 1450000.00,
                'tax' => 145000.00,
                'due_date' => '2025-10-17',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'status' => 'draft',
                'payment_method' => 'debit',
            ],
            [
                'po_number' => 'PPO-2025-019',
                'issue_date' => '2025-09-27',
                'supplier_id' => 4,
                'notes' => 'Regular monthly procurement',
                'total_amount' => 1100000.00,
                'tax' => 110000.00,
                'due_date' => '2025-10-20',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'status' => 'pending',
                'payment_method' => 'transfer',
            ],
            [
                'po_number' => 'PPO-2025-020',
                'issue_date' => '2025-09-28',
                'supplier_id' => 5,
                'notes' => 'Q4 final preparation',
                'total_amount' => 3300000.00,
                'tax' => 330000.00,
                'due_date' => '2025-10-22',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'status' => 'approved',
                'payment_method' => 'credit',
            ],
        ];

        foreach ($prePurchaseOrders as $order) {
            DB::table('pre_purchase_orders')->insert(array_merge($order, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
