<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PurchaseOrdersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $purchaseOrders = [
            [
                'invoice_number' => 'PO-2025-001',
                'issue_date' => '2025-08-25',
                'supplier_id' => 1,
                'notes' => 'Initial stock purchase',
                'due_date' => '2025-09-10',
                'payment_date' => '2025-09-08',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 2500000.00,
                'status' => 'completed',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'PO-2025-002',
                'issue_date' => '2025-08-28',
                'supplier_id' => 2,
                'notes' => 'Coffee products restocking',
                'due_date' => '2025-09-12',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 1850000.00,
                'status' => 'processing',
                'payment_method' => 'credit',
            ],
            [
                'invoice_number' => 'PO-2025-003',
                'issue_date' => '2025-09-01',
                'supplier_id' => 3,
                'notes' => 'Cigarette bulk purchase',
                'due_date' => '2025-09-15',
                'payment_date' => '2025-09-14',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 3200000.00,
                'status' => 'completed',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'PO-2025-004',
                'issue_date' => '2025-09-03',
                'supplier_id' => 4,
                'notes' => 'Tea products purchase',
                'due_date' => '2025-09-18',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 950000.00,
                'status' => 'draft',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'PO-2025-005',
                'issue_date' => '2025-09-05',
                'supplier_id' => 5,
                'notes' => 'Premium coffee selection',
                'due_date' => '2025-09-20',
                'payment_date' => '2025-09-19',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 1750000.00,
                'status' => 'completed',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'PO-2025-006',
                'issue_date' => '2025-09-08',
                'supplier_id' => 6,
                'notes' => 'Monthly cigarette restock',
                'due_date' => '2025-09-22',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 2800000.00,
                'status' => 'processing',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'PO-2025-007',
                'issue_date' => '2025-09-10',
                'supplier_id' => 7,
                'notes' => 'Snack and beverages purchase',
                'due_date' => '2025-09-25',
                'payment_date' => '2025-09-24',
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 1250000.00,
                'status' => 'completed',
                'payment_method' => 'debit',
            ],
            [
                'invoice_number' => 'PO-2025-008',
                'issue_date' => '2025-09-12',
                'supplier_id' => 8,
                'notes' => 'Emergency stock replenishment',
                'due_date' => '2025-09-27',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 1680000.00,
                'status' => 'draft',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'PO-2025-009',
                'issue_date' => '2025-09-15',
                'supplier_id' => 9,
                'notes' => 'Bulk coffee purchase for Q4',
                'due_date' => '2025-09-30',
                'payment_date' => '2025-09-29',
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 2200000.00,
                'status' => 'completed',
                'payment_method' => 'credit',
            ],
            [
                'invoice_number' => 'PO-2025-010',
                'issue_date' => '2025-09-18',
                'supplier_id' => 10,
                'notes' => 'Mixed products order',
                'due_date' => '2025-10-02',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 1420000.00,
                'status' => 'processing',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'PO-2025-011',
                'issue_date' => '2025-09-20',
                'supplier_id' => 11,
                'notes' => 'Year-end stock preparation',
                'due_date' => '2025-10-05',
                'payment_date' => '2025-10-04',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 3100000.00,
                'status' => 'completed',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'PO-2025-012',
                'issue_date' => '2025-09-22',
                'supplier_id' => 12,
                'notes' => 'Tea variety expansion',
                'due_date' => '2025-10-07',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 890000.00,
                'status' => 'draft',
                'payment_method' => 'debit',
            ],
            [
                'invoice_number' => 'PO-2025-013',
                'issue_date' => '2025-09-25',
                'supplier_id' => 13,
                'notes' => 'Premium cigarette brands',
                'due_date' => '2025-10-10',
                'payment_date' => '2025-10-09',
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 4200000.00,
                'status' => 'completed',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'PO-2025-014',
                'issue_date' => '2025-09-27',
                'supplier_id' => 14,
                'notes' => 'New supplier trial order',
                'due_date' => '2025-10-12',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 750000.00,
                'status' => 'processing',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'PO-2025-015',
                'issue_date' => '2025-09-29',
                'supplier_id' => 15,
                'notes' => 'October stock preparation',
                'due_date' => '2025-10-15',
                'payment_date' => '2025-10-14',
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 2650000.00,
                'status' => 'completed',
                'payment_method' => 'credit',
            ],
        ];

        foreach ($purchaseOrders as $order) {
            DB::table('purchase_orders')->insert(array_merge($order, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
