<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SalesOrdersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Contoh: gunakan user id 1 untuk semua sales order
        // Jika ingin berbeda, silakan sesuaikan per baris
        $salesOrders = [
            [
                'invoice_number' => 'SO-2025-001',
                'issue_date' => '2025-09-01',
                'customer_id' => 1,
                'notes' => 'First sales order',
                'due_date' => '2025-09-15',
                'payment_date' => '2025-09-14',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 150000.00,
                'status' => 'completed',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'SO-2025-002',
                'issue_date' => '2025-09-02',
                'customer_id' => 2,
                'notes' => 'Bulk order for coffee products',
                'due_date' => '2025-09-16',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 275000.00,
                'status' => 'draft',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'SO-2025-003',
                'issue_date' => '2025-09-03',
                'customer_id' => 3,
                'notes' => 'Regular monthly order',
                'due_date' => '2025-09-17',
                'payment_date' => '2025-09-16',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 320000.00,
                'status' => 'completed',
                'payment_method' => 'credit',
            ],
            [
                'invoice_number' => 'SO-2025-004',
                'issue_date' => '2025-09-04',
                'customer_id' => 4,
                'notes' => 'Cigarette wholesale order',
                'due_date' => '2025-09-18',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 450000.00,
                'status' => 'draft',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'SO-2025-005',
                'issue_date' => '2025-09-05',
                'customer_id' => 5,
                'notes' => 'Mixed product order',
                'due_date' => '2025-09-19',
                'payment_date' => '2025-09-18',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 180000.00,
                'status' => 'completed',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'SO-2025-006',
                'issue_date' => '2025-09-06',
                'customer_id' => 6,
                'notes' => 'Tea products order',
                'due_date' => '2025-09-20',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 95000.00,
                'status' => 'draft',
                'payment_method' => 'debit',
            ],
            [
                'invoice_number' => 'SO-2025-007',
                'issue_date' => '2025-09-07',
                'customer_id' => 7,
                'notes' => 'Premium coffee selection',
                'due_date' => '2025-09-21',
                'payment_date' => '2025-09-20',
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 225000.00,
                'status' => 'completed',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'SO-2025-008',
                'issue_date' => '2025-09-08',
                'customer_id' => 8,
                'notes' => 'Urgent delivery order',
                'due_date' => '2025-09-22',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 165000.00,
                'status' => 'draft',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'SO-2025-009',
                'issue_date' => '2025-09-09',
                'customer_id' => 9,
                'notes' => 'Corporate order',
                'due_date' => '2025-09-23',
                'payment_date' => '2025-09-22',
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 380000.00,
                'status' => 'completed',
                'payment_method' => 'credit',
            ],
            [
                'invoice_number' => 'SO-2025-010',
                'issue_date' => '2025-09-10',
                'customer_id' => 10,
                'notes' => 'Retail store order',
                'due_date' => '2025-09-24',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 140000.00,
                'status' => 'draft',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'SO-2025-011',
                'issue_date' => '2025-09-11',
                'customer_id' => 11,
                'notes' => 'Special promotion order',
                'due_date' => '2025-09-25',
                'payment_date' => '2025-09-24',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 295000.00,
                'status' => 'completed',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'SO-2025-012',
                'issue_date' => '2025-09-12',
                'customer_id' => 12,
                'notes' => 'Weekly replenishment',
                'due_date' => '2025-09-26',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 125000.00,
                'status' => 'draft',
                'payment_method' => 'debit',
            ],
            [
                'invoice_number' => 'SO-2025-013',
                'issue_date' => '2025-09-13',
                'customer_id' => 13,
                'notes' => 'Export order preparation',
                'due_date' => '2025-09-27',
                'payment_date' => '2025-09-26',
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 520000.00,
                'status' => 'completed',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'SO-2025-014',
                'issue_date' => '2025-09-14',
                'customer_id' => 14,
                'notes' => 'New customer trial order',
                'due_date' => '2025-09-28',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 85000.00,
                'status' => 'draft',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'SO-2025-015',
                'issue_date' => '2025-09-15',
                'customer_id' => 15,
                'notes' => 'Bulk discount order',
                'due_date' => '2025-09-29',
                'payment_date' => '2025-09-28',
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 410000.00,
                'status' => 'completed',
                'payment_method' => 'credit',
            ],
            [
                'invoice_number' => 'SO-2025-016',
                'issue_date' => '2025-09-16',
                'customer_id' => 16,
                'notes' => 'Seasonal product order',
                'due_date' => '2025-09-30',
                'payment_date' => null,
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 195000.00,
                'status' => 'draft',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'SO-2025-017',
                'issue_date' => '2025-09-17',
                'customer_id' => 17,
                'notes' => 'VIP customer order',
                'due_date' => '2025-10-01',
                'payment_date' => '2025-09-30',
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 350000.00,
                'status' => 'completed',
                'payment_method' => 'cash',
            ],
            [
                'invoice_number' => 'SO-2025-018',
                'issue_date' => '2025-09-18',
                'customer_id' => 18,
                'notes' => 'Emergency stock order',
                'due_date' => '2025-10-02',
                'payment_date' => null,
                'created_by' => 2,
                'updated_by' => 2,
                'total_amount' => 175000.00,
                'status' => 'draft',
                'payment_method' => 'debit',
            ],
            [
                'invoice_number' => 'SO-2025-019',
                'issue_date' => '2025-09-19',
                'customer_id' => 19,
                'notes' => 'Quarter end order',
                'due_date' => '2025-10-03',
                'payment_date' => '2025-10-02',
                'created_by' => 3,
                'updated_by' => 3,
                'total_amount' => 485000.00,
                'status' => 'completed',
                'payment_method' => 'transfer',
            ],
            [
                'invoice_number' => 'SO-2025-020',
                'issue_date' => '2025-09-20',
                'customer_id' => 20,
                'notes' => 'Final order of the month',
                'due_date' => '2025-10-04',
                'payment_date' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'total_amount' => 265000.00,
                'status' => 'draft',
                'payment_method' => 'credit',
            ],
        ];

        foreach ($salesOrders as $order) {
            DB::table('sales_orders')->insert(array_merge($order, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
