<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'username' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('admin'),
                'role' => 'superadmin',
                'position' => 'Manager',
                'job_title' => 'Administrator',
                'division' => 'IT',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'useradmin1',
                'email' => 'useradmin1@company.com',
                'password' => Hash::make('user'),
                'role' => 'useradmin',
                'position' => 'Supervisor',
                'job_title' => 'User Administrator',
                'division' => 'IT',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'viewer1',
                'email' => 'viewer1@company.com',
                'password' => Hash::make('user'),
                'role' => 'viewer',
                'position' => 'Staff',
                'job_title' => 'Data Viewer',
                'division' => 'Administration',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'cashier1',
                'email' => 'cashier1@company.com',
                'password' => Hash::make('user'),
                'role' => 'cashier',
                'position' => 'Staff',
                'job_title' => 'Cashier',
                'division' => 'Sales',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'cashier2',
                'email' => 'cashier2@company.com',
                'password' => Hash::make('user'),
                'role' => 'cashier',
                'position' => 'Staff',
                'job_title' => 'Cashier',
                'division' => 'Sales',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'warehouse1',
                'email' => 'warehouse1@company.com',
                'password' => Hash::make('user'),
                'role' => 'warehouse',
                'position' => 'Staff',
                'job_title' => 'Warehouse Staff',
                'division' => 'Warehouse',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'warehouse2',
                'email' => 'warehouse2@company.com',
                'password' => Hash::make('user'),
                'role' => 'warehouse',
                'position' => 'Supervisor',
                'job_title' => 'Warehouse Supervisor',
                'division' => 'Warehouse',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'superadmin1',
                'email' => 'superadmin1@company.com',
                'password' => Hash::make('user'),
                'role' => 'superadmin',
                'position' => 'Manager',
                'job_title' => 'System Administrator',
                'division' => 'IT',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'useradmin2',
                'email' => 'useradmin2@company.com',
                'password' => Hash::make('user'),
                'role' => 'useradmin',
                'position' => 'Staff',
                'job_title' => 'User Management',
                'division' => 'Administration',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'viewer2',
                'email' => 'viewer2@company.com',
                'password' => Hash::make('user'),
                'role' => 'viewer',
                'position' => 'Staff',
                'job_title' => 'Report Viewer',
                'division' => 'Administration',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'manager1',
                'email' => 'manager1@company.com',
                'password' => Hash::make('user'),
                'role' => 'superadmin',
                'position' => 'Manager',
                'job_title' => 'Sales Manager',
                'division' => 'Sales',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'staff1',
                'email' => 'staff1@company.com',
                'password' => Hash::make('user'),
                'role' => 'viewer',
                'position' => 'Staff',
                'job_title' => 'Sales Staff',
                'division' => 'Sales',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'purchaser1',
                'email' => 'purchaser1@company.com',
                'password' => Hash::make('user'),
                'role' => 'useradmin',
                'position' => 'Staff',
                'job_title' => 'Purchasing Staff',
                'division' => 'Purchasing',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'accounting1',
                'email' => 'accounting1@company.com',
                'password' => Hash::make('user'),
                'role' => 'viewer',
                'position' => 'Staff',
                'job_title' => 'Accounting Staff',
                'division' => 'Accounting',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'inventory1',
                'email' => 'inventory1@company.com',
                'password' => Hash::make('user'),
                'role' => 'warehouse',
                'position' => 'Staff',
                'job_title' => 'Inventory Staff',
                'division' => 'Inventory',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'sales1',
                'email' => 'sales1@company.com',
                'password' => Hash::make('user'),
                'role' => 'cashier',
                'position' => 'Staff',
                'job_title' => 'Sales Representative',
                'division' => 'Sales',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'sales2',
                'email' => 'sales2@company.com',
                'password' => Hash::make('user'),
                'role' => 'cashier',
                'position' => 'Staff',
                'job_title' => 'Sales Representative',
                'division' => 'Sales',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'operator1',
                'email' => 'operator1@company.com',
                'password' => Hash::make('user'),
                'role' => 'viewer',
                'position' => 'Staff',
                'job_title' => 'Operator',
                'division' => 'System',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'analyst1',
                'email' => 'analyst1@company.com',
                'password' => Hash::make('user'),
                'role' => 'viewer',
                'position' => 'Staff',
                'job_title' => 'Analyst',
                'division' => 'Data',
                'email_verified_at' => now(),
            ],
            [
                'username' => 'coordinator1',
                'email' => 'coordinator1@company.com',
                'password' => Hash::make('user'),
                'role' => 'useradmin',
                'position' => 'Coordinator',
                'job_title' => 'Sales Coordinator',
                'division' => 'Sales',
                'email_verified_at' => now(),
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert(array_merge($user, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
